begin;

alter view public.admin_users set (security_invoker = true);
revoke all on table public.admin_users from public, anon, authenticated;

alter function public.assign_import_order_number() set search_path = public, pg_temp;
alter function public.calculate_import_order_total(bigint) set search_path = public, pg_temp;
alter function public.delete_trash_products(integer) set search_path = public, pg_temp;
alter function public.find_orders_by_id_part(text) set search_path = public, pg_temp;
alter function public.generate_import_order_number() set search_path = public, pg_temp;
alter function public.generate_next_import_order_number() set search_path = public, pg_temp;
alter function public.get_inventory_valuation() set search_path = public, pg_temp;
alter function public.get_trash_products(integer) set search_path = public, pg_temp;
alter function public.handle_new_user() set search_path = public, pg_temp;
alter function public.is_commission_admin() set search_path = public, pg_temp;
alter function public.merge_duplicate_products(integer) set search_path = public, pg_temp;
alter function public.notify_buylist_manager() set search_path = public, pg_temp;
alter function public.notify_credit_change() set search_path = public, pg_temp;
alter function public.notify_import_manager() set search_path = public, pg_temp;
alter function public.notify_order_manager() set search_path = public, pg_temp;
alter function public.notify_stock_alert() set search_path = public, pg_temp;
alter function public.on_commission_adjustments_change() set search_path = public, pg_temp;
alter function public.on_commission_allocations_change() set search_path = public, pg_temp;
alter function public.recalculate_commission_period_status(uuid) set search_path = public, pg_temp;
alter function public.refresh_commission_period(text) set search_path = public, pg_temp;
alter function public.refresh_commission_period(text, numeric, numeric, boolean) set search_path = public, pg_temp;
alter function public.set_import_order_commission_eligible() set search_path = public, pg_temp;
alter function public.set_order_commission_eligible() set search_path = public, pg_temp;
alter function public.sync_product_prices() set search_path = public, pg_temp;

revoke all on function public.assign_import_order_number() from public, anon, authenticated;
grant execute on function public.assign_import_order_number() to service_role;
revoke all on function public.calculate_import_order_total(bigint) from public, anon, authenticated;
grant execute on function public.calculate_import_order_total(bigint) to service_role;
revoke all on function public.delete_trash_products(integer) from public, anon, authenticated;
grant execute on function public.delete_trash_products(integer) to service_role;
revoke all on function public.find_orders_by_id_part(text) from public, anon, authenticated;
grant execute on function public.find_orders_by_id_part(text) to service_role;
revoke all on function public.generate_import_order_number() from public, anon, authenticated;
grant execute on function public.generate_import_order_number() to service_role;
revoke all on function public.generate_next_import_order_number() from public, anon, authenticated;
grant execute on function public.generate_next_import_order_number() to service_role;
revoke all on function public.get_inventory_valuation() from public, anon, authenticated;
grant execute on function public.get_inventory_valuation() to service_role;
revoke all on function public.get_trash_products(integer) from public, anon, authenticated;
grant execute on function public.get_trash_products(integer) to service_role;
revoke all on function public.handle_new_user() from public, anon, authenticated;
grant execute on function public.handle_new_user() to service_role;
revoke all on function public.is_commission_admin() from public, anon;
grant execute on function public.is_commission_admin() to authenticated, service_role;
revoke all on function public.merge_duplicate_products(integer) from public, anon, authenticated;
grant execute on function public.merge_duplicate_products(integer) to service_role;
revoke all on function public.notify_buylist_manager() from public, anon, authenticated;
grant execute on function public.notify_buylist_manager() to service_role;
revoke all on function public.notify_credit_change() from public, anon, authenticated;
grant execute on function public.notify_credit_change() to service_role;
revoke all on function public.notify_import_manager() from public, anon, authenticated;
grant execute on function public.notify_import_manager() to service_role;
revoke all on function public.notify_order_manager() from public, anon, authenticated;
grant execute on function public.notify_order_manager() to service_role;
revoke all on function public.notify_stock_alert() from public, anon, authenticated;
grant execute on function public.notify_stock_alert() to service_role;
revoke all on function public.on_commission_adjustments_change() from public, anon, authenticated;
grant execute on function public.on_commission_adjustments_change() to service_role;
revoke all on function public.on_commission_allocations_change() from public, anon, authenticated;
grant execute on function public.on_commission_allocations_change() to service_role;
revoke all on function public.recalculate_commission_period_status(uuid) from public, anon, authenticated;
grant execute on function public.recalculate_commission_period_status(uuid) to service_role;
revoke all on function public.refresh_commission_period(text) from public, anon, authenticated;
grant execute on function public.refresh_commission_period(text) to service_role;
revoke all on function public.refresh_commission_period(text, numeric, numeric, boolean) from public, anon, authenticated;
grant execute on function public.refresh_commission_period(text, numeric, numeric, boolean) to service_role;
revoke all on function public.set_import_order_commission_eligible() from public, anon, authenticated;
grant execute on function public.set_import_order_commission_eligible() to service_role;
revoke all on function public.set_order_commission_eligible() from public, anon, authenticated;
grant execute on function public.set_order_commission_eligible() to service_role;
revoke all on function public.sync_product_prices() from public, anon, authenticated;
grant execute on function public.sync_product_prices() to service_role;

commit;
