drop extension if exists "pg_net";

create extension if not exists "pg_trgm" with schema "public";

create type "public"."import_platform" as enum ('Coolstuffinc', 'Cardkingdom', 'Manapool', 'TCG Player', 'EBay', 'Amazon', 'Otro');

create type "public"."import_status" as enum ('Iniciada', 'Procesada', 'Enviada', 'Parcialmente Disponible', 'Disponible', 'Parcialmente Completada', 'Completada', 'Solo Cotización', 'En cotización', 'Cotizada', 'Cotización Aprobada');

create sequence "public"."import_order_seq";

create sequence "public"."import_orders_seq";


  create table "public"."analytics_visits" (
    "id" uuid not null default gen_random_uuid(),
    "source" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."analytics_visits" enable row level security;


  create table "public"."banners" (
    "id" bigint generated by default as identity not null,
    "image_url" text not null,
    "title" text,
    "description" text,
    "link_url" text,
    "button_text" text,
    "display_order" integer default 0,
    "active" boolean default true,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."banners" enable row level security;


  create table "public"."buylist_items" (
    "id" uuid not null default gen_random_uuid(),
    "buylist_id" uuid not null,
    "product_id" uuid not null,
    "quantity" integer not null,
    "offered_price_unit" numeric not null,
    "condition" text default 'NM'::text,
    "is_foil" boolean default false,
    "notes" text,
    "card_name" text,
    "set_name" text,
    "collector_number" text,
    "image_url" text
      );


alter table "public"."buylist_items" enable row level security;


  create table "public"."buylist_orders" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "status" text default 'pending_review'::text,
    "total_offered" numeric not null,
    "admin_notes" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."buylist_orders" enable row level security;


  create table "public"."cart_items" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "product_id" text not null,
    "quantity" integer not null default 1,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."cart_items" enable row level security;


  create table "public"."coupons" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "discount_type" text not null,
    "value" numeric not null,
    "active" boolean default true,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."coupons" enable row level security;


  create table "public"."credit_transactions" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "amount" numeric not null,
    "type" text not null,
    "description" text,
    "reference_id" uuid,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "transaction_type" text default 'general'::text,
    "transaction_desc" text,
    "ref_id" text
      );


alter table "public"."credit_transactions" enable row level security;


  create table "public"."external_prices" (
    "scryfall_id" uuid not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()),
    "tcgplayer_market_normal" numeric default 0,
    "tcgplayer_market_foil" numeric default 0,
    "cardkingdom_retail_normal" numeric default 0,
    "cardkingdom_retail_foil" numeric default 0,
    "cardkingdom_buylist_normal" numeric default 0,
    "cardkingdom_buylist_foil" numeric default 0,
    "cardkingdom_retail_etched" numeric,
    "cardkingdom_id_normal" text,
    "cardkingdom_id_foil" text,
    "tcgplayer_id" text,
    "ignore_ck" boolean default false,
    "cardkingdom_variation" text
      );


alter table "public"."external_prices" enable row level security;


  create table "public"."faqs" (
    "id" bigint generated by default as identity not null,
    "question" text not null,
    "answer" text not null,
    "display_order" integer default 0,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."faqs" enable row level security;


  create table "public"."feedback" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "rating" integer,
    "comment" text,
    "page_url" text,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."feedback" enable row level security;


  create table "public"."import_items" (
    "id" bigint generated by default as identity not null,
    "order_id" bigint,
    "product_name" text not null,
    "image_url" text,
    "quantity" integer default 1,
    "platform" public.import_platform default 'Cardkingdom'::public.import_platform,
    "unit_price" numeric default 0,
    "tax_percent" numeric default 12,
    "shipping_cost" numeric default 0.5,
    "is_available" boolean default false,
    "is_delivered" boolean default false,
    "created_at" timestamp with time zone default now(),
    "set_name" text,
    "collector_number" text,
    "suggested_price" numeric default 0,
    "in_cart" boolean default false
      );


alter table "public"."import_items" enable row level security;


  create table "public"."import_orders" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "order_number" text not null,
    "status" public.import_status default 'Iniciada'::public.import_status,
    "admin_notes" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "paid" boolean not null default false,
    "payment_proof_url" text,
    "payment_status" text default 'pending'::text,
    "credits_used" numeric(10,2) default 0
      );


alter table "public"."import_orders" enable row level security;


  create table "public"."notifications" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "type" text not null,
    "title" text not null,
    "message" text,
    "link" text,
    "is_read" boolean default false,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."notifications" enable row level security;


  create table "public"."order_items" (
    "id" uuid not null default gen_random_uuid(),
    "order_id" uuid not null,
    "product_id" uuid not null,
    "quantity" integer not null,
    "price_at_purchase" numeric not null
      );


alter table "public"."order_items" enable row level security;


  create table "public"."orders" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "status" text default 'pending_payment'::text,
    "total_amount" numeric not null,
    "payment_method" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "tracking_number" text,
    "delivery_notes" text,
    "delivery_method" text,
    "shipping_cost" numeric default 0,
    "shipping_address" jsonb,
    "credits_used" numeric default 0,
    "coupon_code" text,
    "discount_amount" numeric default 0,
    "contact_name" text,
    "contact_lastname" text,
    "contact_phone" text,
    "is_packed" boolean default false,
    "payment_proof_url" text
      );


alter table "public"."orders" enable row level security;


  create table "public"."price_history" (
    "id" uuid not null default gen_random_uuid(),
    "product_id" uuid not null,
    "price" numeric not null,
    "old_price" numeric,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."price_history" enable row level security;


  create table "public"."price_opportunities" (
    "id" bigint generated by default as identity not null,
    "card_name" text not null,
    "set_name" text,
    "image_url" text,
    "tcg_low" numeric,
    "local_price" numeric,
    "diff_percentage" numeric,
    "suggested_action" text,
    "created_at" timestamp with time zone default now(),
    "is_foil" boolean default false
      );


alter table "public"."price_opportunities" enable row level security;


  create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "set_name" text not null,
    "collector_number" text,
    "tcg" text not null,
    "price_usd" numeric not null default 0,
    "stock" integer not null default 0,
    "condition" text default 'NM'::text,
    "finish" text default 'Non-Foil'::text,
    "rarity" text,
    "image_url" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "scryfall_id" text,
    "is_manual_price" boolean default false,
    "language" text default 'English'::text,
    "metadata" jsonb default '{}'::jsonb,
    "restocked_at" timestamp with time zone default now()
      );


alter table "public"."products" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "credits" numeric default 0,
    "role" text default 'user'::text,
    "first_name" text,
    "last_name" text,
    "phone" text,
    "full_name" text,
    "avatar_url" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."saved_items" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "product_id" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."saved_items" enable row level security;


  create table "public"."search_logs" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "query" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."search_logs" enable row level security;


  create table "public"."system_settings" (
    "key" text not null,
    "value" jsonb,
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."system_settings" enable row level security;


  create table "public"."wishlists" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "product_id" uuid,
    "card_name" text not null,
    "set_name" text,
    "image_url" text,
    "is_specific" boolean default true,
    "notified" boolean default false,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."wishlists" enable row level security;

CREATE UNIQUE INDEX analytics_visits_pkey ON public.analytics_visits USING btree (id);

CREATE UNIQUE INDEX banners_pkey ON public.banners USING btree (id);

CREATE UNIQUE INDEX buylist_items_pkey ON public.buylist_items USING btree (id);

CREATE UNIQUE INDEX buylist_orders_pkey ON public.buylist_orders USING btree (id);

CREATE UNIQUE INDEX cart_items_pkey ON public.cart_items USING btree (id);

CREATE UNIQUE INDEX cart_items_user_id_product_id_key ON public.cart_items USING btree (user_id, product_id);

CREATE UNIQUE INDEX coupons_code_key ON public.coupons USING btree (code);

CREATE UNIQUE INDEX coupons_pkey ON public.coupons USING btree (id);

CREATE UNIQUE INDEX credit_transactions_pkey ON public.credit_transactions USING btree (id);

CREATE UNIQUE INDEX external_prices_pkey ON public.external_prices USING btree (scryfall_id);

CREATE UNIQUE INDEX faqs_pkey ON public.faqs USING btree (id);

CREATE UNIQUE INDEX feedback_pkey ON public.feedback USING btree (id);

CREATE INDEX idx_cart_items_product ON public.cart_items USING btree (product_id);

CREATE INDEX idx_cart_items_user ON public.cart_items USING btree (user_id);

CREATE INDEX idx_import_orders_paid ON public.import_orders USING btree (paid);

CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);

CREATE INDEX idx_orders_user_id ON public.orders USING btree (user_id);

CREATE INDEX idx_products_name_trgm ON public.products USING gin (name public.gin_trgm_ops);

CREATE INDEX idx_products_scryfall_id ON public.products USING btree (scryfall_id);

CREATE INDEX idx_products_tcg ON public.products USING btree (tcg);

CREATE INDEX idx_wishlist_name ON public.wishlists USING btree (card_name);

CREATE INDEX idx_wishlist_product ON public.wishlists USING btree (product_id);

CREATE INDEX idx_wishlist_user ON public.wishlists USING btree (user_id);

CREATE UNIQUE INDEX import_items_pkey ON public.import_items USING btree (id);

CREATE UNIQUE INDEX import_orders_order_number_key ON public.import_orders USING btree (order_number);

CREATE UNIQUE INDEX import_orders_pkey ON public.import_orders USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX price_history_pkey ON public.price_history USING btree (id);

CREATE UNIQUE INDEX price_opportunities_pkey ON public.price_opportunities USING btree (id);

CREATE INDEX products_metadata_gin ON public.products USING gin (metadata);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE INDEX products_scryfall_id_idx ON public.products USING btree (scryfall_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX saved_items_pkey ON public.saved_items USING btree (id);

CREATE UNIQUE INDEX saved_items_user_id_product_id_key ON public.saved_items USING btree (user_id, product_id);

CREATE UNIQUE INDEX search_logs_pkey ON public.search_logs USING btree (id);

CREATE UNIQUE INDEX system_settings_pkey ON public.system_settings USING btree (key);

CREATE UNIQUE INDEX unique_product_variant ON public.products USING btree (scryfall_id, finish, condition, language);

CREATE UNIQUE INDEX unique_wishlist_specific ON public.wishlists USING btree (user_id, product_id);

CREATE UNIQUE INDEX wishlists_pkey ON public.wishlists USING btree (id);

alter table "public"."analytics_visits" add constraint "analytics_visits_pkey" PRIMARY KEY using index "analytics_visits_pkey";

alter table "public"."banners" add constraint "banners_pkey" PRIMARY KEY using index "banners_pkey";

alter table "public"."buylist_items" add constraint "buylist_items_pkey" PRIMARY KEY using index "buylist_items_pkey";

alter table "public"."buylist_orders" add constraint "buylist_orders_pkey" PRIMARY KEY using index "buylist_orders_pkey";

alter table "public"."cart_items" add constraint "cart_items_pkey" PRIMARY KEY using index "cart_items_pkey";

alter table "public"."coupons" add constraint "coupons_pkey" PRIMARY KEY using index "coupons_pkey";

alter table "public"."credit_transactions" add constraint "credit_transactions_pkey" PRIMARY KEY using index "credit_transactions_pkey";

alter table "public"."external_prices" add constraint "external_prices_pkey" PRIMARY KEY using index "external_prices_pkey";

alter table "public"."faqs" add constraint "faqs_pkey" PRIMARY KEY using index "faqs_pkey";

alter table "public"."feedback" add constraint "feedback_pkey" PRIMARY KEY using index "feedback_pkey";

alter table "public"."import_items" add constraint "import_items_pkey" PRIMARY KEY using index "import_items_pkey";

alter table "public"."import_orders" add constraint "import_orders_pkey" PRIMARY KEY using index "import_orders_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."price_history" add constraint "price_history_pkey" PRIMARY KEY using index "price_history_pkey";

alter table "public"."price_opportunities" add constraint "price_opportunities_pkey" PRIMARY KEY using index "price_opportunities_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."saved_items" add constraint "saved_items_pkey" PRIMARY KEY using index "saved_items_pkey";

alter table "public"."search_logs" add constraint "search_logs_pkey" PRIMARY KEY using index "search_logs_pkey";

alter table "public"."system_settings" add constraint "system_settings_pkey" PRIMARY KEY using index "system_settings_pkey";

alter table "public"."wishlists" add constraint "wishlists_pkey" PRIMARY KEY using index "wishlists_pkey";

alter table "public"."buylist_items" add constraint "buylist_items_buylist_id_fkey" FOREIGN KEY (buylist_id) REFERENCES public.buylist_orders(id) ON DELETE CASCADE not valid;

alter table "public"."buylist_items" validate constraint "buylist_items_buylist_id_fkey";

alter table "public"."buylist_orders" add constraint "buylist_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."buylist_orders" validate constraint "buylist_orders_user_id_fkey";

alter table "public"."cart_items" add constraint "cart_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."cart_items" validate constraint "cart_items_user_id_fkey";

alter table "public"."cart_items" add constraint "cart_items_user_id_product_id_key" UNIQUE using index "cart_items_user_id_product_id_key";

alter table "public"."coupons" add constraint "coupons_code_key" UNIQUE using index "coupons_code_key";

alter table "public"."credit_transactions" add constraint "credit_transactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."credit_transactions" validate constraint "credit_transactions_user_id_fkey";

alter table "public"."feedback" add constraint "feedback_rating_check" CHECK (((rating >= 1) AND (rating <= 5))) not valid;

alter table "public"."feedback" validate constraint "feedback_rating_check";

alter table "public"."feedback" add constraint "feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."feedback" validate constraint "feedback_user_id_fkey";

alter table "public"."import_items" add constraint "import_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.import_orders(id) ON DELETE CASCADE not valid;

alter table "public"."import_items" validate constraint "import_items_order_id_fkey";

alter table "public"."import_orders" add constraint "import_orders_order_number_key" UNIQUE using index "import_orders_order_number_key";

alter table "public"."import_orders" add constraint "import_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."import_orders" validate constraint "import_orders_user_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

alter table "public"."order_items" add constraint "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE not valid;

alter table "public"."order_items" validate constraint "order_items_order_id_fkey";

alter table "public"."order_items" add constraint "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."order_items" validate constraint "order_items_product_id_fkey";

alter table "public"."orders" add constraint "fk_orders_profiles" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."orders" validate constraint "fk_orders_profiles";

alter table "public"."orders" add constraint "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."orders" validate constraint "orders_user_id_fkey";

alter table "public"."price_history" add constraint "price_history_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."price_history" validate constraint "price_history_product_id_fkey";

alter table "public"."profiles" add constraint "credits_non_negative" CHECK ((credits >= (0)::numeric)) not valid;

alter table "public"."profiles" validate constraint "credits_non_negative";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."saved_items" add constraint "saved_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."saved_items" validate constraint "saved_items_product_id_fkey";

alter table "public"."saved_items" add constraint "saved_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."saved_items" validate constraint "saved_items_user_id_fkey";

alter table "public"."saved_items" add constraint "saved_items_user_id_product_id_key" UNIQUE using index "saved_items_user_id_product_id_key";

alter table "public"."search_logs" add constraint "search_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."search_logs" validate constraint "search_logs_user_id_fkey";

alter table "public"."wishlists" add constraint "unique_wishlist_specific" UNIQUE using index "unique_wishlist_specific";

alter table "public"."wishlists" add constraint "wishlists_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."wishlists" validate constraint "wishlists_product_id_fkey";

alter table "public"."wishlists" add constraint "wishlists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."wishlists" validate constraint "wishlists_user_id_fkey";

set check_function_bodies = off;

create or replace view "public"."admin_users" as  SELECT id
   FROM public.profiles
  WHERE ((role = 'admin'::text) OR (email = 'mjperchezabala@gmail.com'::text));


CREATE OR REPLACE FUNCTION public.approve_buylist_transaction(buylist_id_input uuid, amount_to_credit numeric)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- A. Actualizar estado de la orden
  UPDATE buylist_orders
  SET status = 'completed'
  WHERE id = buylist_id_input;

  -- B. Sumar créditos al usuario
  UPDATE profiles
  SET credits = credits + amount_to_credit
  WHERE id = (SELECT user_id FROM buylist_orders WHERE id = buylist_id_input);

  -- C. Registrar transacción (CORREGIDO: usa 'type' y 'description')
  INSERT INTO credit_transactions (
    user_id, 
    amount, 
    type, 
    description, 
    reference_id
  )
  VALUES (
    (SELECT user_id FROM buylist_orders WHERE id = buylist_id_input),
    amount_to_credit,
    'buylist',  -- Valor para la columna 'type'
    'Venta aprobada (Buylist)', -- Valor para la columna 'description'
    buylist_id_input
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.assign_import_order_number()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  n int;
  candidate text;
begin
  perform pg_advisory_lock(8712346);

  -- Si viene número y ya existe, lo reemplazamos
  if new.order_number is not null then
    if exists (select 1 from public.import_orders where order_number = new.order_number) then
      n := nextval('public.import_order_seq');
      candidate := 'IMP-' || lpad(n::text, 4, '0');
      new.order_number := candidate;
    end if;
  else
    -- Si no viene, asignamos el siguiente de la secuencia
    n := nextval('public.import_order_seq');
    candidate := 'IMP-' || lpad(n::text, 4, '0');
    new.order_number := candidate;
  end if;

  perform pg_advisory_unlock(8712346);
  return new;

exception when others then
  perform pg_advisory_unlock(8712346);
  raise;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.decrement_stock(qty integer, row_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  update products 
  set stock = stock - qty
  where id = row_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_trash_products(batch_size integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    deleted_count int;
BEGIN
    DELETE FROM products
    WHERE id IN (
        SELECT id FROM products p
        WHERE p.tcg = 'Magic'
          AND p.stock = 0
          -- Borramos si NO es manual O si tiene el precio de pánico (99999)
          AND (p.is_manual_price IS NOT TRUE OR p.price_usd >= 99000)
          
          -- 🛡️ PROTECCIONES BLINDADAS
          -- Wishlists (Tiene FK, es UUID)
          AND NOT EXISTS (SELECT 1 FROM wishlists w WHERE w.product_id = p.id)
          -- Carritos (Es TEXT, convertimos el ID del producto a texto para comparar)
          AND NOT EXISTS (SELECT 1 FROM cart_items c WHERE c.product_id = p.id::text)
          -- Saved Items (Tiene FK, es UUID)
          AND NOT EXISTS (SELECT 1 FROM saved_items s WHERE s.product_id = p.id)
          -- Historial de Ventas (Tiene FK, es UUID)
          AND NOT EXISTS (SELECT 1 FROM order_items o WHERE o.product_id = p.id)
          
        LIMIT batch_size
    );
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.find_orders_by_id_part(q text)
 RETURNS TABLE(id uuid)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select o.id
  from public.orders o
  where o.id::text ilike '%' || q || '%'
  limit 200;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_import_order_number()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Solo genera si no viene uno ya (o si queremos forzarlo, lo sobreescribimos)
  NEW.order_number := 'IMP-' || LPAD(nextval('import_orders_seq')::TEXT, 4, '0');
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_next_import_order_number()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  n int := 0;
  candidate text;
begin
  perform pg_advisory_lock(8712345);

  select coalesce(max((regexp_replace(order_number, '^IMP-', ''))::int), 0)
    into n
  from public.import_orders
  where order_number ~ '^IMP-\d{4}$';

  loop
    n := n + 1;
    candidate := 'IMP-' || lpad(n::text, 4, '0');

    exit when not exists (
      select 1 from public.import_orders where order_number = candidate
    );
  end loop;

  perform pg_advisory_unlock(8712345);
  return candidate;

exception when others then
  perform pg_advisory_unlock(8712345);
  raise;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_inventory_valuation()
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN (SELECT COALESCE(SUM(stock * price_usd), 0) FROM products WHERE stock > 0);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_trash_products(batch_size integer)
 RETURNS uuid[]
 LANGUAGE plpgsql
AS $function$
DECLARE
    result uuid[];
BEGIN
    SELECT array_agg(id) INTO result
    FROM (
        SELECT id FROM products p
        WHERE p.tcg = 'Magic'
          AND p.stock = 0
          -- Borramos si NO es manual O si tiene el precio de pánico (99999)
          AND (p.is_manual_price IS NOT TRUE OR p.price_usd >= 99000)
          
          -- 🛡️ PROTECCIONES BLINDADAS (Usando NOT EXISTS)
          -- Wishlists
          AND NOT EXISTS (SELECT 1 FROM wishlists w WHERE w.product_id = p.id)
          -- Carritos (Casteo seguro a UUID)
          AND NOT EXISTS (SELECT 1 FROM cart_items c WHERE c.product_id::uuid = p.id)
          -- Saved Items
          AND NOT EXISTS (SELECT 1 FROM saved_items s WHERE s.product_id::uuid = p.id)
          -- Historial de Ventas
          AND NOT EXISTS (SELECT 1 FROM order_items o WHERE o.product_id = p.id)
          
        LIMIT batch_size
    ) t;
    
    RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, credits, first_name, last_name)
  VALUES (
    new.id, 
    new.email, 
    0, 
    new.raw_user_meta_data->>'first_name', 
    new.raw_user_meta_data->>'last_name'
  );
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.manage_credits(target_user_id uuid, amount_change numeric, transaction_type text, transaction_desc text, ref_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- A. Actualizar el saldo actual del perfil
  UPDATE public.profiles
  SET credits = credits + amount_change
  WHERE id = target_user_id;

  -- B. Registrar en el historial
  INSERT INTO public.credit_transactions (user_id, amount, type, description, reference_id)
  VALUES (target_user_id, amount_change, transaction_type, transaction_desc, ref_id);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.merge_duplicate_products(batch_size integer DEFAULT 100)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    r RECORD;
    original_id UUID;
    duplicate_id UUID;
    processed_count INT := 0;
BEGIN
    FOR r IN 
        SELECT name, set_name, finish, condition, language, count(*) 
        FROM products 
        WHERE tcg = 'Magic'
          AND name NOT LIKE '%(ARCHIVADO)%' -- Ignoramos los que ya nos rendimos
        GROUP BY name, set_name, finish, condition, language
        HAVING count(*) > 1
        LIMIT batch_size
    LOOP
        -- 1. Identificar Original (El que tiene stock o es más viejo)
        SELECT id INTO original_id
        FROM products
        WHERE name = r.name AND set_name = r.set_name AND finish = r.finish 
          AND condition = r.condition AND language = r.language
          AND name NOT LIKE '%(ARCHIVADO)%'
        ORDER BY stock DESC, created_at ASC
        LIMIT 1;

        -- 2. Identificar Duplicados para eliminar
        FOR duplicate_id IN 
            SELECT id FROM products 
            WHERE name = r.name AND set_name = r.set_name AND finish = r.finish 
              AND condition = r.condition AND language = r.language
              AND id != original_id
        LOOP
            -- Mover Carritos (Sumar si existe, mover si no)
            UPDATE cart_items c1
            SET quantity = c1.quantity + c2.quantity
            FROM cart_items c2
            WHERE c1.user_id = c2.user_id AND c1.product_id = original_id::text AND c2.product_id = duplicate_id::text;
            
            DELETE FROM cart_items WHERE product_id = duplicate_id::text; -- Borrar conflicto
            UPDATE cart_items SET product_id = original_id::text WHERE product_id = duplicate_id::text; -- Mover resto

            -- Mover Wishlists
            DELETE FROM wishlists WHERE product_id = duplicate_id AND user_id IN (SELECT user_id FROM wishlists WHERE product_id = original_id);
            UPDATE wishlists SET product_id = original_id WHERE product_id = duplicate_id;

            -- Mover Saved Items
            BEGIN
                DELETE FROM saved_items WHERE product_id = duplicate_id::text AND user_id IN (SELECT user_id FROM saved_items WHERE product_id = original_id::text);
                UPDATE saved_items SET product_id = original_id::text WHERE product_id = duplicate_id::text;
            EXCEPTION WHEN OTHERS THEN NULL; END;

            -- 3. INTENTO FINAL DE BORRADO O ARCHIVADO
            BEGIN
                DELETE FROM products WHERE id = duplicate_id;
            EXCEPTION WHEN foreign_key_violation THEN
                -- SI FALLA EL BORRADO, LO RENOMBRAMOS PARA ROMPER EL BUCLE
                UPDATE products 
                SET 
                    stock = 0, 
                    is_manual_price = true,
                    name = name || ' (ARCHIVADO)', 
                    scryfall_id = NULL 
                WHERE id = duplicate_id;
            END;
        END LOOP;
        
        processed_count := processed_count + 1;
    END LOOP;

    RETURN 'Se procesaron ' || processed_count || ' grupos restantes.';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_buylist_manager()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  admin_id UUID;
BEGIN
  -- NUEVA SOLICITUD (Avisar Admin)
  IF (TG_OP = 'INSERT') THEN
    FOR admin_id IN SELECT id FROM admin_users LOOP
      INSERT INTO notifications (user_id, type, title, message, link)
      VALUES (
        admin_id, 'buylist', 'Nueva Solicitud de Venta',
        'Solicitud #' || SUBSTRING(NEW.id::text, 1, 8),
        '/admin/buylists/' || NEW.id -- CORREGIDO: 'buylists' con S
      );
    END LOOP;
  END IF;

  -- CAMBIO DE ESTADO (Avisar Usuario)
  IF (TG_OP = 'UPDATE' AND OLD.status <> NEW.status) THEN
    INSERT INTO notifications (user_id, type, title, message, link)
    VALUES (
      NEW.user_id, 'buylist', 'Solicitud Actualizada',
      'Tu solicitud cambió a: ' || UPPER(NEW.status),
      '/profile?tab=quotes'
    );
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_credit_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF OLD.credits <> NEW.credits THEN
    DECLARE
      diff NUMERIC;
      msg TEXT;
    BEGIN
      diff := NEW.credits - OLD.credits;
      
      IF diff > 0 THEN
        msg := 'Se acreditaron $' || diff || ' créditos en tu cuenta.';
      ELSE
        msg := 'Se utilizaron $' || ABS(diff) || ' créditos de tu saldo.';
      END IF;
      
      INSERT INTO notifications (user_id, type, title, message, link)
      VALUES (
        NEW.id, 
        'credit', 
        'Saldo Actualizado', 
        msg, 
        '/profile?tab=history' -- PUNTO 1: Link ajustado
      );
    END;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_import_manager()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  admin_id UUID;
BEGIN
  -- A) NUEVO PEDIDO (Avisar Admin -> /admin/imports/ID)
  IF (TG_OP = 'INSERT') THEN
    FOR admin_id IN SELECT id FROM admin_users LOOP
      INSERT INTO notifications (user_id, type, title, message, link)
      VALUES (
        admin_id, 
        'import', 
        'Nuevo Pedido al Exterior',
        'Orden: ' || NEW.order_number,
        '/admin/imports/' || NEW.id
      );
    END LOOP;
  END IF;

  -- B) CAMBIO DE ESTADO (Avisar Usuario -> /profile/imports/ID)
  IF (TG_OP = 'UPDATE' AND OLD.status <> NEW.status) THEN
    INSERT INTO notifications (user_id, type, title, message, link)
    VALUES (
      NEW.user_id, 
      'import', 
      'Importación Actualizada',
      'Tu orden ' || NEW.order_number || ' ahora está: ' || NEW.status,
      '/profile/imports/' || NEW.id -- ✅ Link corregido
    );
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_order_manager()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  admin_id UUID;
BEGIN
  -- CASO A: NUEVA VENTA (PUNTO 6: Avisar al Admin)
  IF (TG_OP = 'INSERT') THEN
    FOR admin_id IN SELECT id FROM admin_users LOOP
      INSERT INTO notifications (user_id, type, title, message, link)
      VALUES (
        admin_id,
        'order',
        'Nueva Venta de Stock',
        'Nueva orden #' || SUBSTRING(NEW.id::text, 1, 8) || ' por $' || NEW.total_amount,
        '/admin/orders/' || NEW.id
      );
    END LOOP;
  END IF;

  -- CASO B: CAMBIO DE ESTADO (PUNTO 7: Avisar Usuario)
  -- Importante: El status puede cambiar de 'pending_payment' a 'paid', etc.
  IF (TG_OP = 'UPDATE' AND OLD.status <> NEW.status) THEN
    INSERT INTO notifications (user_id, type, title, message, link)
    VALUES (
      NEW.user_id,
      'order',
      'Actualización de Pedido',
      'Tu pedido #' || SUBSTRING(NEW.id::text, 1, 8) || ' ha cambiado a estado: ' || UPPER(NEW.status),
      '/profile?tab=stock'
    );
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_stock_alert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  subscriber RECORD;
BEGIN
  -- Solo actuar si el stock era 0 (o menor) y ahora es positivo
  IF (OLD.stock <= 0 AND NEW.stock > 0) THEN
    
    -- Buscar todos los usuarios que tienen este producto en su wishlist
    FOR subscriber IN 
      SELECT user_id FROM wishlists WHERE product_id = NEW.id
    LOOP
      INSERT INTO notifications (user_id, type, title, message, link)
      VALUES (
        subscriber.user_id,
        'stock',
        '¡Producto Disponible!',
        'El producto "' || NEW.name || '" ya está en stock. ¡Corre antes de que se agote!',
        '/product/' || NEW.id
      );
    END LOOP;
    
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.restore_stock(order_id_input uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  item record;
begin
  -- Recorrer cada item de la orden y devolverlo al stock
  for item in select * from order_items where order_id = order_id_input loop
    update products
    set stock = stock + item.quantity
    where id = item.product_id;
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_product_prices()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Actualizar cartas Normales (Solo si CK manda un precio mayor a 0)
  IF NEW.cardkingdom_retail_normal > 0 THEN
      UPDATE products
      SET price_usd = NEW.cardkingdom_retail_normal
      WHERE scryfall_id::text = NEW.scryfall_id::text
        AND finish ILIKE '%Non-Foil%'
        AND is_manual_price = false;
  END IF;

  -- Actualizar cartas Foil (Solo si CK manda un precio mayor a 0)
  IF NEW.cardkingdom_retail_foil > 0 THEN
      UPDATE products
      SET price_usd = NEW.cardkingdom_retail_foil
      WHERE scryfall_id::text = NEW.scryfall_id::text
        AND (finish ILIKE '%Foil%' AND finish NOT ILIKE '%Non-Foil%')
        AND is_manual_price = false;
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.transfer_credits(recipient_email text, amount numeric, note text DEFAULT ''::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  v_sender_id uuid := auth.uid();
  v_sender_email text;
  v_recipient_id uuid;
  v_sender_balance numeric;
  v_tracking_id text := gen_random_uuid(); -- Generamos un ID único para este par de movimientos
begin
  -- Validaciones
  if amount <= 0 then
    raise exception 'El monto debe ser mayor a 0.';
  end if;

  -- Obtener email del remitente para mostrarlo al receptor
  select email into v_sender_email from profiles where id = v_sender_id;

  -- Buscar destinatario
  select id into v_recipient_id from profiles where email = recipient_email;
  
  if v_recipient_id is null then
    raise exception 'El usuario destinatario no existe.';
  end if;

  if v_recipient_id = v_sender_id then
    raise exception 'No puedes transferirte a ti mismo.';
  end if;

  -- Verificar saldo
  select credits into v_sender_balance from profiles where id = v_sender_id;
  
  if v_sender_balance < amount then
    raise exception 'Saldo insuficiente.';
  end if;

  -- EJECUTAR TRANSFERENCIA
  update profiles set credits = credits - amount where id = v_sender_id;
  update profiles set credits = coalesce(credits, 0) + amount where id = v_recipient_id;

  -- REGISTRAR HISTORIAL (Con Rastreo, Nota y Remitente)
  
  -- Log para el Emisor
  insert into credit_transactions (user_id, amount, type, transaction_desc, ref_id, created_at)
  values (
    v_sender_id, 
    -amount, 
    'transfer_sent', 
    'Enviado a ' || recipient_email || (case when note <> '' then ' - Nota: ' || note else '' end), 
    v_tracking_id, 
    now()
  );

  -- Log para el Receptor (Ahora ve quién se lo mandó)
  insert into credit_transactions (user_id, amount, type, transaction_desc, ref_id, created_at)
  values (
    v_recipient_id, 
    amount, 
    'transfer_received', 
    'Recibido de ' || v_sender_email || (case when note <> '' then ' - Nota: ' || note else '' end), 
    v_tracking_id, 
    now()
  );

end;
$function$
;

CREATE OR REPLACE FUNCTION public.user_accept_buylist_offer(buylist_id_input uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  order_data RECORD;
BEGIN
  SELECT * INTO order_data
  FROM public.buylist_orders
  WHERE id = buylist_id_input;

  IF order_data.user_id != auth.uid() THEN RAISE EXCEPTION 'Sin permiso.'; END IF;
  IF order_data.status != 'waiting_user_approval' THEN RAISE EXCEPTION 'Estado incorrecto.'; END IF;

  -- SOLO CAMBIAR ESTADO
  UPDATE public.buylist_orders
  SET status = 'waiting_receipt' -- Esperando que el usuario traiga las cartas
  WHERE id = buylist_id_input;
END;
$function$
;

grant delete on table "public"."analytics_visits" to "anon";

grant insert on table "public"."analytics_visits" to "anon";

grant references on table "public"."analytics_visits" to "anon";

grant select on table "public"."analytics_visits" to "anon";

grant trigger on table "public"."analytics_visits" to "anon";

grant truncate on table "public"."analytics_visits" to "anon";

grant update on table "public"."analytics_visits" to "anon";

grant delete on table "public"."analytics_visits" to "authenticated";

grant insert on table "public"."analytics_visits" to "authenticated";

grant references on table "public"."analytics_visits" to "authenticated";

grant select on table "public"."analytics_visits" to "authenticated";

grant trigger on table "public"."analytics_visits" to "authenticated";

grant truncate on table "public"."analytics_visits" to "authenticated";

grant update on table "public"."analytics_visits" to "authenticated";

grant delete on table "public"."analytics_visits" to "service_role";

grant insert on table "public"."analytics_visits" to "service_role";

grant references on table "public"."analytics_visits" to "service_role";

grant select on table "public"."analytics_visits" to "service_role";

grant trigger on table "public"."analytics_visits" to "service_role";

grant truncate on table "public"."analytics_visits" to "service_role";

grant update on table "public"."analytics_visits" to "service_role";

grant delete on table "public"."banners" to "anon";

grant insert on table "public"."banners" to "anon";

grant references on table "public"."banners" to "anon";

grant select on table "public"."banners" to "anon";

grant trigger on table "public"."banners" to "anon";

grant truncate on table "public"."banners" to "anon";

grant update on table "public"."banners" to "anon";

grant delete on table "public"."banners" to "authenticated";

grant insert on table "public"."banners" to "authenticated";

grant references on table "public"."banners" to "authenticated";

grant select on table "public"."banners" to "authenticated";

grant trigger on table "public"."banners" to "authenticated";

grant truncate on table "public"."banners" to "authenticated";

grant update on table "public"."banners" to "authenticated";

grant delete on table "public"."banners" to "service_role";

grant insert on table "public"."banners" to "service_role";

grant references on table "public"."banners" to "service_role";

grant select on table "public"."banners" to "service_role";

grant trigger on table "public"."banners" to "service_role";

grant truncate on table "public"."banners" to "service_role";

grant update on table "public"."banners" to "service_role";

grant delete on table "public"."buylist_items" to "anon";

grant insert on table "public"."buylist_items" to "anon";

grant references on table "public"."buylist_items" to "anon";

grant select on table "public"."buylist_items" to "anon";

grant trigger on table "public"."buylist_items" to "anon";

grant truncate on table "public"."buylist_items" to "anon";

grant update on table "public"."buylist_items" to "anon";

grant delete on table "public"."buylist_items" to "authenticated";

grant insert on table "public"."buylist_items" to "authenticated";

grant references on table "public"."buylist_items" to "authenticated";

grant select on table "public"."buylist_items" to "authenticated";

grant trigger on table "public"."buylist_items" to "authenticated";

grant truncate on table "public"."buylist_items" to "authenticated";

grant update on table "public"."buylist_items" to "authenticated";

grant delete on table "public"."buylist_items" to "service_role";

grant insert on table "public"."buylist_items" to "service_role";

grant references on table "public"."buylist_items" to "service_role";

grant select on table "public"."buylist_items" to "service_role";

grant trigger on table "public"."buylist_items" to "service_role";

grant truncate on table "public"."buylist_items" to "service_role";

grant update on table "public"."buylist_items" to "service_role";

grant delete on table "public"."buylist_orders" to "anon";

grant insert on table "public"."buylist_orders" to "anon";

grant references on table "public"."buylist_orders" to "anon";

grant select on table "public"."buylist_orders" to "anon";

grant trigger on table "public"."buylist_orders" to "anon";

grant truncate on table "public"."buylist_orders" to "anon";

grant update on table "public"."buylist_orders" to "anon";

grant delete on table "public"."buylist_orders" to "authenticated";

grant insert on table "public"."buylist_orders" to "authenticated";

grant references on table "public"."buylist_orders" to "authenticated";

grant select on table "public"."buylist_orders" to "authenticated";

grant trigger on table "public"."buylist_orders" to "authenticated";

grant truncate on table "public"."buylist_orders" to "authenticated";

grant update on table "public"."buylist_orders" to "authenticated";

grant delete on table "public"."buylist_orders" to "service_role";

grant insert on table "public"."buylist_orders" to "service_role";

grant references on table "public"."buylist_orders" to "service_role";

grant select on table "public"."buylist_orders" to "service_role";

grant trigger on table "public"."buylist_orders" to "service_role";

grant truncate on table "public"."buylist_orders" to "service_role";

grant update on table "public"."buylist_orders" to "service_role";

grant delete on table "public"."cart_items" to "anon";

grant insert on table "public"."cart_items" to "anon";

grant references on table "public"."cart_items" to "anon";

grant select on table "public"."cart_items" to "anon";

grant trigger on table "public"."cart_items" to "anon";

grant truncate on table "public"."cart_items" to "anon";

grant update on table "public"."cart_items" to "anon";

grant delete on table "public"."cart_items" to "authenticated";

grant insert on table "public"."cart_items" to "authenticated";

grant references on table "public"."cart_items" to "authenticated";

grant select on table "public"."cart_items" to "authenticated";

grant trigger on table "public"."cart_items" to "authenticated";

grant truncate on table "public"."cart_items" to "authenticated";

grant update on table "public"."cart_items" to "authenticated";

grant delete on table "public"."cart_items" to "service_role";

grant insert on table "public"."cart_items" to "service_role";

grant references on table "public"."cart_items" to "service_role";

grant select on table "public"."cart_items" to "service_role";

grant trigger on table "public"."cart_items" to "service_role";

grant truncate on table "public"."cart_items" to "service_role";

grant update on table "public"."cart_items" to "service_role";

grant delete on table "public"."coupons" to "anon";

grant insert on table "public"."coupons" to "anon";

grant references on table "public"."coupons" to "anon";

grant select on table "public"."coupons" to "anon";

grant trigger on table "public"."coupons" to "anon";

grant truncate on table "public"."coupons" to "anon";

grant update on table "public"."coupons" to "anon";

grant delete on table "public"."coupons" to "authenticated";

grant insert on table "public"."coupons" to "authenticated";

grant references on table "public"."coupons" to "authenticated";

grant select on table "public"."coupons" to "authenticated";

grant trigger on table "public"."coupons" to "authenticated";

grant truncate on table "public"."coupons" to "authenticated";

grant update on table "public"."coupons" to "authenticated";

grant delete on table "public"."coupons" to "service_role";

grant insert on table "public"."coupons" to "service_role";

grant references on table "public"."coupons" to "service_role";

grant select on table "public"."coupons" to "service_role";

grant trigger on table "public"."coupons" to "service_role";

grant truncate on table "public"."coupons" to "service_role";

grant update on table "public"."coupons" to "service_role";

grant delete on table "public"."credit_transactions" to "anon";

grant insert on table "public"."credit_transactions" to "anon";

grant references on table "public"."credit_transactions" to "anon";

grant select on table "public"."credit_transactions" to "anon";

grant trigger on table "public"."credit_transactions" to "anon";

grant truncate on table "public"."credit_transactions" to "anon";

grant update on table "public"."credit_transactions" to "anon";

grant delete on table "public"."credit_transactions" to "authenticated";

grant insert on table "public"."credit_transactions" to "authenticated";

grant references on table "public"."credit_transactions" to "authenticated";

grant select on table "public"."credit_transactions" to "authenticated";

grant trigger on table "public"."credit_transactions" to "authenticated";

grant truncate on table "public"."credit_transactions" to "authenticated";

grant update on table "public"."credit_transactions" to "authenticated";

grant delete on table "public"."credit_transactions" to "service_role";

grant insert on table "public"."credit_transactions" to "service_role";

grant references on table "public"."credit_transactions" to "service_role";

grant select on table "public"."credit_transactions" to "service_role";

grant trigger on table "public"."credit_transactions" to "service_role";

grant truncate on table "public"."credit_transactions" to "service_role";

grant update on table "public"."credit_transactions" to "service_role";

grant delete on table "public"."external_prices" to "anon";

grant insert on table "public"."external_prices" to "anon";

grant references on table "public"."external_prices" to "anon";

grant select on table "public"."external_prices" to "anon";

grant trigger on table "public"."external_prices" to "anon";

grant truncate on table "public"."external_prices" to "anon";

grant update on table "public"."external_prices" to "anon";

grant delete on table "public"."external_prices" to "authenticated";

grant insert on table "public"."external_prices" to "authenticated";

grant references on table "public"."external_prices" to "authenticated";

grant select on table "public"."external_prices" to "authenticated";

grant trigger on table "public"."external_prices" to "authenticated";

grant truncate on table "public"."external_prices" to "authenticated";

grant update on table "public"."external_prices" to "authenticated";

grant delete on table "public"."external_prices" to "service_role";

grant insert on table "public"."external_prices" to "service_role";

grant references on table "public"."external_prices" to "service_role";

grant select on table "public"."external_prices" to "service_role";

grant trigger on table "public"."external_prices" to "service_role";

grant truncate on table "public"."external_prices" to "service_role";

grant update on table "public"."external_prices" to "service_role";

grant delete on table "public"."faqs" to "anon";

grant insert on table "public"."faqs" to "anon";

grant references on table "public"."faqs" to "anon";

grant select on table "public"."faqs" to "anon";

grant trigger on table "public"."faqs" to "anon";

grant truncate on table "public"."faqs" to "anon";

grant update on table "public"."faqs" to "anon";

grant delete on table "public"."faqs" to "authenticated";

grant insert on table "public"."faqs" to "authenticated";

grant references on table "public"."faqs" to "authenticated";

grant select on table "public"."faqs" to "authenticated";

grant trigger on table "public"."faqs" to "authenticated";

grant truncate on table "public"."faqs" to "authenticated";

grant update on table "public"."faqs" to "authenticated";

grant delete on table "public"."faqs" to "service_role";

grant insert on table "public"."faqs" to "service_role";

grant references on table "public"."faqs" to "service_role";

grant select on table "public"."faqs" to "service_role";

grant trigger on table "public"."faqs" to "service_role";

grant truncate on table "public"."faqs" to "service_role";

grant update on table "public"."faqs" to "service_role";

grant delete on table "public"."feedback" to "anon";

grant insert on table "public"."feedback" to "anon";

grant references on table "public"."feedback" to "anon";

grant select on table "public"."feedback" to "anon";

grant trigger on table "public"."feedback" to "anon";

grant truncate on table "public"."feedback" to "anon";

grant update on table "public"."feedback" to "anon";

grant delete on table "public"."feedback" to "authenticated";

grant insert on table "public"."feedback" to "authenticated";

grant references on table "public"."feedback" to "authenticated";

grant select on table "public"."feedback" to "authenticated";

grant trigger on table "public"."feedback" to "authenticated";

grant truncate on table "public"."feedback" to "authenticated";

grant update on table "public"."feedback" to "authenticated";

grant delete on table "public"."feedback" to "service_role";

grant insert on table "public"."feedback" to "service_role";

grant references on table "public"."feedback" to "service_role";

grant select on table "public"."feedback" to "service_role";

grant trigger on table "public"."feedback" to "service_role";

grant truncate on table "public"."feedback" to "service_role";

grant update on table "public"."feedback" to "service_role";

grant delete on table "public"."import_items" to "anon";

grant insert on table "public"."import_items" to "anon";

grant references on table "public"."import_items" to "anon";

grant select on table "public"."import_items" to "anon";

grant trigger on table "public"."import_items" to "anon";

grant truncate on table "public"."import_items" to "anon";

grant update on table "public"."import_items" to "anon";

grant delete on table "public"."import_items" to "authenticated";

grant insert on table "public"."import_items" to "authenticated";

grant references on table "public"."import_items" to "authenticated";

grant select on table "public"."import_items" to "authenticated";

grant trigger on table "public"."import_items" to "authenticated";

grant truncate on table "public"."import_items" to "authenticated";

grant update on table "public"."import_items" to "authenticated";

grant delete on table "public"."import_items" to "service_role";

grant insert on table "public"."import_items" to "service_role";

grant references on table "public"."import_items" to "service_role";

grant select on table "public"."import_items" to "service_role";

grant trigger on table "public"."import_items" to "service_role";

grant truncate on table "public"."import_items" to "service_role";

grant update on table "public"."import_items" to "service_role";

grant delete on table "public"."import_orders" to "anon";

grant insert on table "public"."import_orders" to "anon";

grant references on table "public"."import_orders" to "anon";

grant select on table "public"."import_orders" to "anon";

grant trigger on table "public"."import_orders" to "anon";

grant truncate on table "public"."import_orders" to "anon";

grant update on table "public"."import_orders" to "anon";

grant delete on table "public"."import_orders" to "authenticated";

grant insert on table "public"."import_orders" to "authenticated";

grant references on table "public"."import_orders" to "authenticated";

grant select on table "public"."import_orders" to "authenticated";

grant trigger on table "public"."import_orders" to "authenticated";

grant truncate on table "public"."import_orders" to "authenticated";

grant update on table "public"."import_orders" to "authenticated";

grant delete on table "public"."import_orders" to "service_role";

grant insert on table "public"."import_orders" to "service_role";

grant references on table "public"."import_orders" to "service_role";

grant select on table "public"."import_orders" to "service_role";

grant trigger on table "public"."import_orders" to "service_role";

grant truncate on table "public"."import_orders" to "service_role";

grant update on table "public"."import_orders" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."price_history" to "anon";

grant insert on table "public"."price_history" to "anon";

grant references on table "public"."price_history" to "anon";

grant select on table "public"."price_history" to "anon";

grant trigger on table "public"."price_history" to "anon";

grant truncate on table "public"."price_history" to "anon";

grant update on table "public"."price_history" to "anon";

grant delete on table "public"."price_history" to "authenticated";

grant insert on table "public"."price_history" to "authenticated";

grant references on table "public"."price_history" to "authenticated";

grant select on table "public"."price_history" to "authenticated";

grant trigger on table "public"."price_history" to "authenticated";

grant truncate on table "public"."price_history" to "authenticated";

grant update on table "public"."price_history" to "authenticated";

grant delete on table "public"."price_history" to "service_role";

grant insert on table "public"."price_history" to "service_role";

grant references on table "public"."price_history" to "service_role";

grant select on table "public"."price_history" to "service_role";

grant trigger on table "public"."price_history" to "service_role";

grant truncate on table "public"."price_history" to "service_role";

grant update on table "public"."price_history" to "service_role";

grant delete on table "public"."price_opportunities" to "anon";

grant insert on table "public"."price_opportunities" to "anon";

grant references on table "public"."price_opportunities" to "anon";

grant select on table "public"."price_opportunities" to "anon";

grant trigger on table "public"."price_opportunities" to "anon";

grant truncate on table "public"."price_opportunities" to "anon";

grant update on table "public"."price_opportunities" to "anon";

grant delete on table "public"."price_opportunities" to "authenticated";

grant insert on table "public"."price_opportunities" to "authenticated";

grant references on table "public"."price_opportunities" to "authenticated";

grant select on table "public"."price_opportunities" to "authenticated";

grant trigger on table "public"."price_opportunities" to "authenticated";

grant truncate on table "public"."price_opportunities" to "authenticated";

grant update on table "public"."price_opportunities" to "authenticated";

grant delete on table "public"."price_opportunities" to "service_role";

grant insert on table "public"."price_opportunities" to "service_role";

grant references on table "public"."price_opportunities" to "service_role";

grant select on table "public"."price_opportunities" to "service_role";

grant trigger on table "public"."price_opportunities" to "service_role";

grant truncate on table "public"."price_opportunities" to "service_role";

grant update on table "public"."price_opportunities" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."saved_items" to "anon";

grant insert on table "public"."saved_items" to "anon";

grant references on table "public"."saved_items" to "anon";

grant select on table "public"."saved_items" to "anon";

grant trigger on table "public"."saved_items" to "anon";

grant truncate on table "public"."saved_items" to "anon";

grant update on table "public"."saved_items" to "anon";

grant delete on table "public"."saved_items" to "authenticated";

grant insert on table "public"."saved_items" to "authenticated";

grant references on table "public"."saved_items" to "authenticated";

grant select on table "public"."saved_items" to "authenticated";

grant trigger on table "public"."saved_items" to "authenticated";

grant truncate on table "public"."saved_items" to "authenticated";

grant update on table "public"."saved_items" to "authenticated";

grant delete on table "public"."saved_items" to "service_role";

grant insert on table "public"."saved_items" to "service_role";

grant references on table "public"."saved_items" to "service_role";

grant select on table "public"."saved_items" to "service_role";

grant trigger on table "public"."saved_items" to "service_role";

grant truncate on table "public"."saved_items" to "service_role";

grant update on table "public"."saved_items" to "service_role";

grant delete on table "public"."search_logs" to "anon";

grant insert on table "public"."search_logs" to "anon";

grant references on table "public"."search_logs" to "anon";

grant select on table "public"."search_logs" to "anon";

grant trigger on table "public"."search_logs" to "anon";

grant truncate on table "public"."search_logs" to "anon";

grant update on table "public"."search_logs" to "anon";

grant delete on table "public"."search_logs" to "authenticated";

grant insert on table "public"."search_logs" to "authenticated";

grant references on table "public"."search_logs" to "authenticated";

grant select on table "public"."search_logs" to "authenticated";

grant trigger on table "public"."search_logs" to "authenticated";

grant truncate on table "public"."search_logs" to "authenticated";

grant update on table "public"."search_logs" to "authenticated";

grant delete on table "public"."search_logs" to "service_role";

grant insert on table "public"."search_logs" to "service_role";

grant references on table "public"."search_logs" to "service_role";

grant select on table "public"."search_logs" to "service_role";

grant trigger on table "public"."search_logs" to "service_role";

grant truncate on table "public"."search_logs" to "service_role";

grant update on table "public"."search_logs" to "service_role";

grant delete on table "public"."system_settings" to "anon";

grant insert on table "public"."system_settings" to "anon";

grant references on table "public"."system_settings" to "anon";

grant select on table "public"."system_settings" to "anon";

grant trigger on table "public"."system_settings" to "anon";

grant truncate on table "public"."system_settings" to "anon";

grant update on table "public"."system_settings" to "anon";

grant delete on table "public"."system_settings" to "authenticated";

grant insert on table "public"."system_settings" to "authenticated";

grant references on table "public"."system_settings" to "authenticated";

grant select on table "public"."system_settings" to "authenticated";

grant trigger on table "public"."system_settings" to "authenticated";

grant truncate on table "public"."system_settings" to "authenticated";

grant update on table "public"."system_settings" to "authenticated";

grant delete on table "public"."system_settings" to "service_role";

grant insert on table "public"."system_settings" to "service_role";

grant references on table "public"."system_settings" to "service_role";

grant select on table "public"."system_settings" to "service_role";

grant trigger on table "public"."system_settings" to "service_role";

grant truncate on table "public"."system_settings" to "service_role";

grant update on table "public"."system_settings" to "service_role";

grant delete on table "public"."wishlists" to "anon";

grant insert on table "public"."wishlists" to "anon";

grant references on table "public"."wishlists" to "anon";

grant select on table "public"."wishlists" to "anon";

grant trigger on table "public"."wishlists" to "anon";

grant truncate on table "public"."wishlists" to "anon";

grant update on table "public"."wishlists" to "anon";

grant delete on table "public"."wishlists" to "authenticated";

grant insert on table "public"."wishlists" to "authenticated";

grant references on table "public"."wishlists" to "authenticated";

grant select on table "public"."wishlists" to "authenticated";

grant trigger on table "public"."wishlists" to "authenticated";

grant truncate on table "public"."wishlists" to "authenticated";

grant update on table "public"."wishlists" to "authenticated";

grant delete on table "public"."wishlists" to "service_role";

grant insert on table "public"."wishlists" to "service_role";

grant references on table "public"."wishlists" to "service_role";

grant select on table "public"."wishlists" to "service_role";

grant trigger on table "public"."wishlists" to "service_role";

grant truncate on table "public"."wishlists" to "service_role";

grant update on table "public"."wishlists" to "service_role";


  create policy "Admin select analytics"
  on "public"."analytics_visits"
  as permissive
  for select
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'mjperchezabala@gmail.com'::text));



  create policy "Allow anon insert analytics"
  on "public"."analytics_visits"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "Admin gestiona banners tabla"
  on "public"."banners"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "Public ver banners"
  on "public"."banners"
  as permissive
  for select
  to public
using (true);



  create policy "Admin actualiza items buylist"
  on "public"."buylist_items"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Users manage own buylist items"
  on "public"."buylist_items"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.buylist_orders
  WHERE ((buylist_orders.id = buylist_items.buylist_id) AND (buylist_orders.user_id = auth.uid())))));



  create policy "Admin manages all buylists"
  on "public"."buylist_orders"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Users manage own buylists"
  on "public"."buylist_orders"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



  create policy "Usuarios pueden actualizar sus items"
  on "public"."cart_items"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Usuarios pueden borrar sus items"
  on "public"."cart_items"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Usuarios pueden insertar sus items"
  on "public"."cart_items"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Usuarios pueden ver sus propios items"
  on "public"."cart_items"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "cart_items_delete"
  on "public"."cart_items"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "cart_items_insert"
  on "public"."cart_items"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "cart_items_select"
  on "public"."cart_items"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "cart_items_update"
  on "public"."cart_items"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Admin borra cupones"
  on "public"."coupons"
  as permissive
  for delete
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Admin inserta cupones"
  on "public"."coupons"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));



  create policy "Admin ve cupones"
  on "public"."coupons"
  as permissive
  for select
  to public
using (true);



  create policy "Lectura Publica Cupones"
  on "public"."coupons"
  as permissive
  for select
  to public
using (true);



  create policy "Admin ve todo"
  on "public"."credit_transactions"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Usuarios ven sus movimientos"
  on "public"."credit_transactions"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Public read prices"
  on "public"."external_prices"
  as permissive
  for select
  to public
using (true);



  create policy "Service role updates"
  on "public"."external_prices"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "Universal Read Prices"
  on "public"."external_prices"
  as permissive
  for select
  to public
using (true);



  create policy "Faqs son públicas para leer"
  on "public"."faqs"
  as permissive
  for select
  to public
using (true);



  create policy "Usuarios autenticados pueden editar faqs"
  on "public"."faqs"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Anyone writes feedback"
  on "public"."feedback"
  as permissive
  for insert
  to public
with check (true);



  create policy "Cualquiera puede enviar feedback"
  on "public"."feedback"
  as permissive
  for insert
  to public
with check (true);



  create policy "Solo admins ven feedback"
  on "public"."feedback"
  as permissive
  for select
  to public
using ((auth.uid() IN ( SELECT profiles.id
   FROM public.profiles
  WHERE (profiles.role = 'admin'::text))));



  create policy "Users can create feedback"
  on "public"."feedback"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Admin gestiona todos los items"
  on "public"."import_items"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "Users can create items for their own orders"
  on "public"."import_items"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.import_orders
  WHERE ((import_orders.id = import_items.order_id) AND (import_orders.user_id = auth.uid())))));



  create policy "Users can view items from their own orders"
  on "public"."import_items"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.import_orders
  WHERE ((import_orders.id = import_items.order_id) AND (import_orders.user_id = auth.uid())))));



  create policy "Usuario ve items de sus ordenes"
  on "public"."import_items"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.import_orders
  WHERE ((import_orders.id = import_items.order_id) AND (import_orders.user_id = auth.uid())))));



  create policy "Admin gestiona todas las ordenes"
  on "public"."import_orders"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "Users can create their own import orders"
  on "public"."import_orders"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Users can view their own import orders"
  on "public"."import_orders"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Usuario ve sus propias ordenes"
  on "public"."import_orders"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Admins pueden crear notificaciones"
  on "public"."notifications"
  as permissive
  for insert
  to public
with check (true);



  create policy "System inserts notifications"
  on "public"."notifications"
  as permissive
  for insert
  to public
with check (true);



  create policy "Users can see own notifications"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can update own notifications"
  on "public"."notifications"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users see own notifications"
  on "public"."notifications"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users update own notifications"
  on "public"."notifications"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Usuarios pueden marcar como leídas"
  on "public"."notifications"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Usuarios ven sus propias notificaciones"
  on "public"."notifications"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Admin puede ver todos los items"
  on "public"."order_items"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Permitir borrar items a usuarios autenticados"
  on "public"."order_items"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Usuarios crean items"
  on "public"."order_items"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.user_id = auth.uid())))));



  create policy "Usuarios ven sus items"
  on "public"."order_items"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.user_id = auth.uid())))));



  create policy "Admin modifica ordenes"
  on "public"."orders"
  as permissive
  for update
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Admin puede ver todas las ordenes"
  on "public"."orders"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Admin ve todas las ordenes"
  on "public"."orders"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Permitir borrar orders a usuarios autenticados"
  on "public"."orders"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Usuarios crean ordenes"
  on "public"."orders"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Usuarios ven sus propias ordenes"
  on "public"."orders"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Historial público"
  on "public"."price_history"
  as permissive
  for select
  to public
using (true);



  create policy "Insertar historial"
  on "public"."price_history"
  as permissive
  for insert
  to public
with check (true);



  create policy "Insertar script local"
  on "public"."price_opportunities"
  as permissive
  for insert
  to public
with check (true);



  create policy "Solo admin gestiona oportunidades"
  on "public"."price_opportunities"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "Permitir Borrado"
  on "public"."products"
  as permissive
  for delete
  to public
using (true);



  create policy "Permitir Carga Masiva"
  on "public"."products"
  as permissive
  for insert
  to public
with check (true);



  create policy "Permitir Edicion"
  on "public"."products"
  as permissive
  for update
  to public
using (true);



  create policy "Public Read Access"
  on "public"."products"
  as permissive
  for select
  to public
using (true);



  create policy "Admin ve perfiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Admin ve todos los perfiles"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Usuarios autenticados ven perfiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Usuarios pueden editar su propio perfil"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Ver perfiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Usuarios agregan items guardados"
  on "public"."saved_items"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Usuarios borran sus items guardados"
  on "public"."saved_items"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Usuarios ven sus items guardados"
  on "public"."saved_items"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Cualquiera puede registrar búsquedas"
  on "public"."search_logs"
  as permissive
  for insert
  to public
with check (true);



  create policy "Solo admin ve logs"
  on "public"."search_logs"
  as permissive
  for select
  to public
using ((auth.uid() IN ( SELECT profiles.id
   FROM public.profiles
  WHERE (profiles.email = 'mjperchezabala@gmail.com'::text))));



  create policy "Admin gestiona Settings"
  on "public"."system_settings"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Lectura Publica Settings"
  on "public"."system_settings"
  as permissive
  for select
  to public
using (true);



  create policy "Admin ve todo"
  on "public"."wishlists"
  as permissive
  for select
  to public
using (true);



  create policy "Lectura global de wishlists"
  on "public"."wishlists"
  as permissive
  for select
  to public
using (true);



  create policy "Usuarios modifican su wishlist"
  on "public"."wishlists"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


CREATE TRIGGER on_buylist_change AFTER INSERT OR UPDATE ON public.buylist_orders FOR EACH ROW EXECUTE FUNCTION public.notify_buylist_manager();

CREATE TRIGGER on_external_price_update AFTER UPDATE ON public.external_prices FOR EACH ROW EXECUTE FUNCTION public.sync_product_prices();

CREATE TRIGGER trigger_sync_product_prices AFTER INSERT OR UPDATE ON public.external_prices FOR EACH ROW EXECUTE FUNCTION public.sync_product_prices();

CREATE TRIGGER on_import_change AFTER INSERT OR UPDATE ON public.import_orders FOR EACH ROW EXECUTE FUNCTION public.notify_import_manager();

CREATE TRIGGER set_import_order_number BEFORE INSERT ON public.import_orders FOR EACH ROW EXECUTE FUNCTION public.generate_import_order_number();

CREATE TRIGGER trg_assign_import_order_number BEFORE INSERT ON public.import_orders FOR EACH ROW EXECUTE FUNCTION public.assign_import_order_number();

CREATE TRIGGER on_order_change AFTER INSERT OR UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.notify_order_manager();

CREATE TRIGGER on_product_restock AFTER UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.notify_stock_alert();

CREATE TRIGGER on_credit_change AFTER UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.notify_credit_change();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Admin gestiona banners"
  on "storage"."objects"
  as permissive
  for all
  to public
using (((bucket_id = 'banners'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))))
with check (((bucket_id = 'banners'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))));



  create policy "Cualquiera ve banners"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'banners'::text));



  create policy "Give users authenticated access to folder 1ifhysk_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'products'::text));



  create policy "Give users authenticated access to folder 1ifhysk_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'products'::text));



  create policy "Give users authenticated access to folder 1ifhysk_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'products'::text));



  create policy "Give users authenticated access to folder 1ifhysk_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'products'::text));



  create policy "Lectura pública de comprobantes"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'payment_proofs'::text));



  create policy "Usuarios pueden subir comprobantes"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'payment_proofs'::text));



